#ifndef COUNTRY_STRINGS_HPP
#define COUNTRY_STRINGS_HPP


const char* countryNames[] = {
    "Not supported",
    "Czech Republic",
    "France",
    "Germany",
    "Spain",
    "Italy",
    "Netherlands",
    "Poland",
    "Slovakia",
    "Belarus",
    "Moldova",
    "Russia",
    "Ukraine",
    "Belgium",
    "Bulgaria",
    "Denmark",
    "Finland",
    "United Kingdom",
    "Greece",
    "Croatia",
    "Hungary",
    "Israel",
    "Luxembourg",
    "Macedonia",
    "Norway",
    "Portugal",
    "Romania",
    "Serbia",
    "Azerbaijan",
    "Georgia",
    "Kazakhstan",
    "Lithuania",
    "Turkmenistan",
    "Uzbekistan",
    "Latvia",
    "Estonia",
    "Albania",
    "Austria",
    "Bosnia and Herzegovina",
    "Ireland",
    "Iceland",
    "Vatican",
    "Malta",
    "Sweden",
    "Switzerland",
    "Cyprus",
    "Turkey",
    "Slovenia",
    "Montenegro",
    "Kosovo",
    "Andorra",
    "Armenia",
    "Monaco",
    "Liechtenstein",
    "San Marino",
    "Aland",

    "Reserved",
    "Reserved",
    "Reserved",

    "China",
    "In Bahrain",
    "South Korea",
    "Lebanon",
    "Nepal",
    "Thailand",
    "Pakistan",
    "United Arab Emirates",
    "Bhutan",
    "Oman",
    "North Korea",
    "Philippines",
    "Cambodia",
    "Qatar",
    "Kyrgyzstan",
    "Maldives",
    "Malaysia",
    "Mongolia",
    "Saudi Arabia",
    "Brunei",
    "Laos",
    "Japan",

    "Reserved",

    "Palestinian State",
    "Tajikistan",
    "Kuwait",
    "Syria",
    "India",
    "Indonesia",
    "Afghanistan",
    "Sri Lanka",
    "Iraq",
    "Vietnam",
    "Iran",
    "Yemen",
    "Jordan",
    "Burma",
    "Sikkim",
    "Bangladesh",
    "Singapore",
    "East Timor",

    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",

    "Egypt",
    "Libya",
    "Sudan",
    "Tunisia",
    "Algeria",
    "Morocco",
    "Ethiopia",
    "Eritrea",
    "Somalia Democratic",
    "Djibouti",
    "Kenya",
    "Tanzania",
    "Uganda",
    "Rwanda",
    "Burundi",
    "Seychelles",
    "Chad",
    "Central African",
    "Cameroon",
    "Equatorial Guinea",
    "Gabon",
    "Congo",
    "Democratic Republic of the Congo",
    "Sao Tome and Principe",
    "Mauritania",
    "Western Sahara",
    "Senegal",
    "Gambia",
    "Mali",
    "Burkina Faso",
    "Guinea",
    "Guinea-Bissau",
    "Cape Verde",
    "Sierra Leone",
    "Liberia",
    "Ivory Coast",
    "Ghana",
    "Togo",
    "Benin",
    "Niger",
    "Zambia",
    "Angola",
    "Zimbabwe",
    "Malawi",
    "Mozambique",
    "Botswana",
    "Namibia",
    "South Africa",
    "Swaziland",
    "Lesotho",
    "Madagascar",
    "Comoros",
    "Mauritius",
    "Nigeria",
    "South Sudan",
    "Saint Helena",
    "Mayotte",
    "Reunion",
    "Canary",
    "AZORES",
    "Madeira",

     "Reserved",
     "Reserved",
     "Reserved",     
     "Reserved",

    "Canada",
    "Greenland Nuuk",
    "Pierre and Miquelon",
    "United States",
    "Bermuda",
    "Mexico",
    "Guatemala",
    "Belize",
    "El Salvador",
    "Honduras",
    "Nicaragua",
    "Costa Rica",
    "Panama",
    "The Bahamas",
    "The Turks and Caicos Islands",
    "Cuba",
    "Jamaica",
    "Cayman Islands",
    "Haiti",
    "The Dominican",
    "Puerto Rico",
    "The United States Virgin Islands",
    "The British Virgin Islands",
    "Anguilla The Valley",
    "Antigua and Barbuda",
    "Collectivit�� de Saint-Martin",
    "Autonomous country",
    "Saint-Barth��lemy",
    "Saint Kitts and Nevis",
    "Montserrat",
    "Guadeloupe",
    "Dominica",
    "Martinique",
    "St. Lucia",
    "Saint Vincent and the Grenadines",
    "Grenada",
    "Barbados",
    "Trinidad and Tobago",
    "Curacao",
    "Aruba",
    "Netherlands Antilles",
    "Colombia",
    "Venezuela",
    "Guyana",
    "Suriname",
    "Guyane Francaise",
    "Ecuador",
    "Peru",
    "Bolivia",
    "Paraguay",
    "Chile",
    "Brazil",
    "Uruguay",
    "Argentina",

    "Reserved",
    "Reserved",
    "Reserved", 
    "Reserved",

    "Australia",
    "New Zealand",
    "Papua New Guinea",
    "Solomonen",
    "Vanuatu",
    "New Caledonia",
    "Palau",
    "Federated States of Micronesia",
    "Marshall Island",
    "Commonwealth of the Northern Mariana Islands",
    "The Territory of Guahan",
    "Nauru",
    "Kiribati",
    "Fiji",
    "Tonga",
    "Tuvalu",
    "Wallis et Futuna",
    "The Independent State of Samoa",
    "Eastern Samoa",
    "Tokelau",
    "Niue",
    "The Cook Islands",
    "French Polynesia",
    "Pitcairn Islands",
    "Hawaii State",

    "Reserved",
    "CRIndex",
    "Unrecognized",
    "ALL"

};

#endif